apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui-data
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi